pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/mattlol85/Fitz-Net.git']]])
            }
        }
        stage('Install Dependencies') {
            steps {
                    sh 'npm install'
                
            }
        }
        stage('Build') {
            steps {
                    sh 'npm run build'
                
            }
        }
        stage('Publish') {
            echo "Done!"
        }
    }
}
