pipeline {
    agent {
        label "raspberrypi"
    }
    stages {
        stage('Checkout') {
            steps {
                dir('RPI-Webserver-HardwareAPI'){
                checkout([$class: 'GitSCM', branches: [[name: 'dev/panelRpiAPI']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/mattlol85/Fitz-Net.git']]])
                }
            }
        }
        stage('Build') {
            steps {
                dir('RPI-Webserver-HardwareAPI'){
                sh 'mvn clean package'
                }
            }
        }
    }
}
