pipeline {
    agent {
        label "raspberrypi"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'dev/panelRpiAPI']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/mattlol85/Fitz-Net.git']]])
            }
        }
        stage('Build') {
            steps {
                dir('RPI-Webserver-HardwareAPI') {
                    sh 'sudo mvn clean package'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
}
